spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
            show-sql: true
    datasource:
        driver-class-name: org.postgresql.Driver
    mail:
        host: smtp.gmail.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
springdoc:
    swagger-ui:
        path: /api/v1/swagger
    api-docs:
        path: /api/v1/api-docs
server:
    port: 8080
