spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
            show-sql: true
    datasource:
        url: jdbc:postgres://db:5432/postgres
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver
springdoc:
    swagger-ui:
        path: /api/v1/swagger
    api-docs:
        path: /api/v1/api-docs
server:
    port: 8080
